name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        config: [release_x64, release_x86, release_x64dll, release_x86dll]
    runs-on: ubuntu-22.04
    steps:
    - name: support 32bit
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get -qq update
        sudo apt-get -y install gcc-multilib g++-multilib
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"
    - name: Build 3rdparty
      run: |
        cd 3rdparty
        premake5 gmake2
        ./build.sh
    - name: Generate build files
      run: |
        premake5 gmake2
    - name: Build
      run: |
        make -j$(nproc) config=${{ matrix.config }}
    - name: Test
      run: |
        ./build/${{ matrix.config }}/TDissUnitTester --gtest_output=xml:test_results_${{ matrix.config }}.xml
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.config }}
        path: test_results_${{ matrix.config }}.xml
